[project]
name = "prime_utils"
version = "0.1.0"
description = "Prime number utilities"
authors = [{name = "Example Author"}]
readme = "README.md"
requires-python = ">=3.8"

[project.optional-dependencies]
plot = ["matplotlib"]

[project.scripts]
prime = "prime_utils.prime_cli:main"
